#!/usr/bin/python
# -*- coding: utf-8 -*-
# @cond LICENSE
#
# Copyright [2010-2013] Institute of Nuclear Physics PAN, Krakow, Poland
#
# Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#
# @endcond LICENSE
import os
import traceback

"""
@author Maciej Nabozny <mn@mnabozny.pl>
"""

import sys

try:
    sys.path.append('/usr/lib/cc1/')
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "cm.settings")
    from cm.tools.vnc import start, stop
    from common.tools.system import *
except Exception, e:
    traceback.print_exc()
    print str(e)
    print "ERROR: Cannot import CM database model. Probably unconfigured!"
    sys.exit(1)


if __name__ == "__main__":
    check_my_login('root')

    if len(sys.argv) == 2 and sys.argv[1] == "start":
        sys.exit(start())
    elif len(sys.argv) == 2 and sys.argv[1] == "stop":
        sys.exit(stop())
    else:
        print "Usage: %s mount|umount" % sys.argv[0]
        sys.exit(1)
