#!/usr/bin/python
# -*- coding: utf-8 -*-
# @cond LICENSE
#
# Copyright [2010-2013] Institute of Nuclear Physics PAN, Krakow, Poland
#
# Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#
# @endcond LICENSE

"""
@author Maciej Nabozny <mn@mnabozny.pl>
"""

import subprocess
import os
import sys
sys.path.append('/usr/lib/cc1/')
from cm import config

def create():
    if 'HOST' not in config.DATABASES['default']:
        subprocess.call(['su', 'postgres', '-c', "psql -c \"CREATE USER cc1;\""])
        subprocess.call(['su', 'postgres', '-c', "psql -c \"CREATE DATABASE cm WITH OWNER cc1;\""])
    return 0

def remove():
    if 'HOST' not in config.DATABASES['default']:
        subprocess.call(['su', 'postgres', '-c', "psql -c \"REVOKE ALL PRIVILEGES ON DATABASE cm FROM cc1;\""])
    return 0

def purge():
    remove()
    subprocess.call(['su', 'postgres', '-c', "psql -c \"DROP DATABASE cm;\""])
    return 0

if __name__ == "__main__":
    if len(sys.argv) == 2 and sys.argv[1] == 'create':
        sys.exit(create())
    elif len(sys.argv) == 2 and sys.argv[1] == 'remove':
        sys.exit(remove())
    elif len(sys.argv) == 2 and sys.argv[1] == 'purge':
        sys.exit(purge())
    else:
        print "Usage: %s [create|remove|purge]" % sys.argv[0]

