#!/bin/bash

### BEGIN INIT INFO
# Provides:             cc1-cm
# Required-Start:       $remote_fs $syslog
# Required-Stop:        $remote_fs $syslog
# Should-Start:         apache2 libvirt-bin postgresql quagga ssh
# Default-Start:        2 3 4 5
# Default-Stop:         0 6
# Short-Description:    CC1 Node configuration
### END INIT INFO

set -e

function start() {
    echo "Starting CC1 CM NoVnc proxy..."
    if [ -f /var/run/cc1/cm-vnc/proxy.pid ] ; then
        echo "Proxy already running!"
    else
        /usr/lib/cc1/cm-vnc/proxy.py &
        echo -n $! > /var/run/cc1/cm-vnc/proxy.pid
    fi
}

function stop() {
    echo "Stopping CC1 CM..."
    if [ -f /var/run/cc1/cm-vnc/proxy.pid ] ; then
        kill -15 `cat /var/run/cc1/cm-vnc/proxy.pid` || true
        rm /var/run/cc1/cm-vnc/proxy.pid
    fi
}

case "$1" in
    start)
        start
        ;;

    stop)
        stop
        ;;

    restart)
        stop
        start
        ;;

    *)
        echo "Usage: $0 [start|stop|restart]"
        exit 1
esac

exit 0
