#!/usr/bin/python
# -*- coding: utf-8 -*-
# @cond LICENSE
#
# Copyright [2010-2013] Institute of Nuclear Physics PAN, Krakow, Poland
#
# Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#
# @endcond LICENSE

"""
@author Maciej Nabozny <mn@mnabozny.pl>
"""

import subprocess
import os
import sys
import shutil
import hashlib
import time

def configure():
    shutil.copyfile('/usr/lib/cc1/wi/config.example', '/etc/cc1/wi/config.example')
    if os.path.exists('/etc/cc1/wi/config.py'):
        print "ERROR: Web Interface alredy configured"
        return 0
    
    example = open('/etc/cc1/wi/config.example', 'r')
    config = ''
    for line in example.readlines():
        if 'WI_SECRET_KEY' in line:
            config = config + line.replace('WI_SECRET_KEY', hashlib.sha1(str(time.time())).hexdigest())
        else:
            config = config + line

    conf_file = open('/etc/cc1/wi/config.py', 'w')
    conf_file.write(config)
    conf_file.close()

    os.symlink('/etc/cc1/wi/config.py', '/usr/lib/cc1/wi/config.py')
    
    return 0
    
def remove():
    if os.path.exists('/usr/lib/cc1/wi/config.py'):
        os.unlink('/usr/lib/cc1/wi/config.py')
    return 0

def purge():
    remove()
    if os.path.exists('/etc/cc1/wi/config.py'):
        os.remove('/etc/cc1/wi/config.py')
        
    if os.path.exists('/etc/cc1/wi/config.example'):
        os.remove('/etc/cc1/wi/config.example')
    return 0


if __name__ == "__main__":
    if len(sys.argv) == 2 and sys.argv[1] == 'configure':
        sys.exit(configure())
    elif len(sys.argv) == 2 and sys.argv[1] == 'remove':
        sys.exit(remove())
    elif len(sys.argv) == 2 and sys.argv[1] == 'purge':
        sys.exit(purge())
    else:
        print "Usage:   %s [configure|remove|purge]" % sys.argv[0]
        sys.exit(1)

