#!/usr/bin/python
# -*- coding: utf-8 -*-
# @cond LICENSE
#
# Copyright [2010-2013] Institute of Nuclear Physics PAN, Krakow, Poland
#
# Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#
# @endcond LICENSE

"""
@author Maciej Nabozny <mn@mnabozny.pl>
"""

import sys
sys.path.append('/usr/lib/cc1/')
config = __import__("%s.settings" % sys.argv[2])
from common.tools.db_psql import *

if __name__ == "__main__":
    if len(sys.argv) == 3 and sys.argv[1] == 'create':
        sys.exit(create(config.settings, sys.argv[2]))
    elif len(sys.argv) == 3 and sys.argv[1] == 'remove':
        sys.exit(remove(config.settings, sys.argv[2]))
    elif len(sys.argv) == 3 and sys.argv[1] == 'purge':
        sys.exit(purge(config.settings, sys.argv[2]))
    else:
        print "Usage: %s create|remove|purge" % sys.argv[0]

