#!/usr/bin/python

import sys
import subprocess
import netifaces

print str(sys.argv)
if __name__ == '__main__':
    if 'remove' in sys.argv:
        log = open('/var/log/cc1/cm_install.log', 'a')

        r = subprocess.call('cc1_cm_setup_config remove', shell=True, stdout=log)
        r = subprocess.call('cc1_cm_setup_db_psql remove', shell=True, stdout=log)
        r = subprocess.call('cc1_cm_setup_apache disable', shell=True, stdout=log)

        r = subprocess.call('cc1_setup_networking remove', shell=True, stdout=log)
        log.close()
        sys.exit(0)
    elif 'purge' in sys.argv:
        log = open('/var/log/cc1/cm_install.log', 'a')

        r = subprocess.call('cc1_cm_setup_config purge', shell=True, stdout=log)
        r = subprocess.call('cc1_cm_setup_db_psql purge', shell=True, stdout=log)
        r = subprocess.call('cc1_cm_setup_apache purge', shell=True, stdout=log)

        r = subprocess.call('cc1_setup_networking purge', shell=True, stdout=log)
        log.close()
        sys.exit(0)
    else:
        print "Use cc1 tools (cc1_...) to reconfigure services!"
        sys.exit(0)

