#!/usr/bin/python

import sys
import subprocess

if __name__ == '__main__':
    if 'remove' in sys.argv:
        log = open('/var/log/cc1/cm_install.log', 'a')

        r = subprocess.call('cc1_setup_config remove clm', shell=True, stdout=log)
        r = subprocess.call('cc1_setup_db_psql remove clm', shell=True, stdout=log)
        r = subprocess.call('cc1_setup_apache disable clm', shell=True, stdout=log)

        log.close()
        sys.exit(0)
    elif 'purge' in sys.argv:
        log = open('/var/log/cc1/cm_install.log', 'a')

        r = subprocess.call('cc1_setup_config purge clm', shell=True, stdout=log)
        r = subprocess.call('cc1_setup_db_psql purge clm', shell=True, stdout=log)
        r = subprocess.call('cc1_setup_apache purge clm', shell=True, stdout=log)

        log.close()
        sys.exit(0)
    else:
        print "Use cc1 tools (cc1_...) to reconfigure services!"
        sys.exit(0)

