#!/usr/bin/python
# -*- coding: utf-8 -*-
# @cond LICENSE
#
# Copyright [2010-2013] Institute of Nuclear Physics PAN, Krakow, Poland
#
# Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#
# @endcond LICENSE

"""
@author Maciej Nabozny <mn@mnabozny.pl>
"""

import subprocess
import os
import sys

def enable():
    subprocess.call('a2enmod ssl', shell=True)
    subprocess.call('a2dissite default', shell=True)
    subprocess.call('a2ensite clm', shell=True)
    subprocess.call('service apache2 restart', shell=True)
    return 0

def disable():
    subprocess.call('a2dissite clm', shell=True)
    subprocess.call('service apache2 restart', shell=True)
    return 0

def purge():
    disable()
    os.remove('/etc/apache2/sites-available/clm')

if __name__ == "__main__":
    if len(sys.argv) == 2 and sys.argv[1] == 'enable':
        sys.exit(enable())
    elif len(sys.argv) == 2 and sys.argv[1] == 'disable':
        sys.exit(disable())
    elif len(sys.argv) == 2 and sys.argv[1] == 'purge':
        sys.exit(purge())
    else:
        print "Usage: %s [enable|disable|purge]" % sys.argv[0]
