#!/usr/bin/python

import os
import sys
import debconf
import subprocess
import commands
import datetime
import shutil
import logging

if __name__ == "__main__":
    if 'remove' in sys.argv:
        log = open('/var/log/cc1/ec2_install.log', 'a')

        r = subprocess.call('cc1_ec2_setup_config remove', shell=True, stdout=log)
        r = subprocess.call('cc1_ec2_setup_apache disable', shell=True, stdout=log)
        r = subprocess.call('cc1_ec2_setup_cleaner disable', shell=True, stdout=log)

        log.close()
        sys.exit(0)
    elif 'purge' in sys.argv:
        log = open('/var/log/cc1/ec2_install.log', 'a')

        r = subprocess.call('cc1_ec2_setup_config purge', shell=True, stdout=log)
        r = subprocess.call('cc1_ec2_setup_apache purge', shell=True, stdout=log)
        r = subprocess.call('cc1_ec2_setup_cleaner disable', shell=True, stdout=log)

        log.close()
        sys.exit(0)
    else:
        print "Use cc1 tools (cc1_...) to reconfigure services!"
        sys.exit(0)

