#!/usr/bin/python
# -*- coding: utf-8 -*-
# @cond LICENSE
#
# Copyright [2010-2013] Institute of Nuclear Physics PAN, Krakow, Poland
#
# Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#
# @endcond LICENSE

"""
@author Maciej Nabozny <mn@mnabozny.pl>
"""

import os
import sys
import shutil


def configure():
    shutil.copyfile('/usr/lib/cc1/cm-vnc/config.example', '/etc/cc1/cm-vnc/config.example')
    if os.path.exists('/etc/cc1/cm-vnc/config.py'):
        # Create symlink, if not exists
        if not os.path.exists('/usr/lib/cc1/cm-vnc/config.py'):
                os.symlink('/etc/cc1/cm-vnc/config.py', '/usr/lib/cc1/cm-vnc/config.py')

        print "WARNING: CM-VNC alredy configured"
        return 0

    shutil.copyfile('/etc/cc1/cm-vnc/config.example', '/etc/cc1/cm-vnc/config.py')

    os.symlink('/etc/cc1/cm-vnc/config.py', '/usr/lib/cc1/cm-vnc/config.py')

    return 0


def remove():
    if os.path.exists('/usr/lib/cc1/cm-vnc/config.py'):
        os.unlink('/usr/lib/cc1/cm-vnc/config.py')
    return 0


def purge():
    remove()
    if os.path.exists('/etc/cc1/cm-vnc/config.py'):
        os.remove('/etc/cc1/cm-vnc/config.py')

    if os.path.exists('/etc/cc1/cm-vnc/config.example'):
        os.remove('/etc/cc1/cm-vnc/config.example')
    return 0


if __name__ == "__main__":
    if len(sys.argv) == 2 and sys.argv[1] == 'configure':
        sys.exit(configure())
    elif len(sys.argv) == 2 and sys.argv[1] == 'remove':
        sys.exit(remove())
    elif len(sys.argv) == 2 and sys.argv[1] == 'purge':
        sys.exit(purge())
    else:
        print "Usage:   %s [configure|remove|purge]" % sys.argv[0]
        sys.exit(1)

