#!/usr/bin/python

import sys
import subprocess
import netifaces

if __name__ == '__main__':
    if 'remove' in sys.argv:
        log = open('/var/log/cc1/cm_install.log', 'a')

        r = subprocess.call('cc1_setup_config remove wi', shell=True, stdout=log)
        r = subprocess.call('cc1_setup_apache disable wi', shell=True, stdout=log)
        log.close()
        sys.exit(0)
    elif 'purge' in sys.argv:
        log = open('/var/log/cc1/cm_install.log', 'a')

        r = subprocess.call('cc1_setup_config purge wi', shell=True, stdout=log)
        r = subprocess.call('cc1_setup_apache purge wi', shell=True, stdout=log)
        log.close()
        sys.exit(0)
    else:
        print "Use cc1 tools (cc1_...) to reconfigure services!"
        sys.exit(0)

