#!/usr/bin/python
# -*- coding: utf-8 -*-
# @cond LICENSE
#
# Copyright [2010-2013] Institute of Nuclear Physics PAN, Krakow, Poland
#
# Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#
# @endcond LICENSE

"""
@author Maciej Nabozny <mn@mnabozny.pl>
"""

import sys
sys.path.append('/usr/lib/cc1')
from node.tools import libvirt_tools

if __name__ == "__main__":
    try:
        if len(sys.argv) == 7 and sys.argv[1] == 'configure':
            # driver, transport, username, address, suffix
            sys.exit(libvirt_tools.configure(sys.argv[2],
                                             sys.argv[3],
                                             sys.argv[4],
                                             sys.argv[5],
                                             sys.argv[6]))
        elif len(sys.argv) == 2 and sys.argv[1] == 'remove':
            sys.exit(libvirt_tools.remove())
        elif len(sys.argv) == 2 and sys.argv[1] == 'purge':
            sys.exit(libvirt_tools.purge())
        else:
            print "Usage: %s configure " % sys.argv[0]
            print "       %s remove|purge " % sys.argv[0]
            print "       Where:"
            print "       - libvirt_connection_string is full url. E.g.:"
            print "         qemu+ssh://cc1@my_hostname/system"
            sys.exit(1)

    except Exception as e:
        print >> sys.stderr, "ERROR: %s" % str(e)
        sys.exit(10)


