#!/usr/bin/python
# -*- coding: utf-8 -*-
# @cond LICENSE
#
# Copyright [2010-2013] Institute of Nuclear Physics PAN, Krakow, Poland
#
# Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#
# @endcond LICENSE

"""
@author Maciej Nabozny <mn@mnabozny.pl>
"""

import sys


def set_value(key, value):
    print "NODE: Updating config: %s:%s" % (key, value)
    config = open('/etc/cc1/node/config.py', 'r')
    lines = []
    for line in config.readlines():
        if line[-1] == '\n':
            line = line[:-1]

        if line.startswith(key):
            lines.append(key + '="' + str(value) + '"')
        else:
            lines.append(line)
    config.close()

    config = open('/etc/cc1/node/config.py', 'w')
    config.write('\n'.join(lines))
    config.close()
    return 0


if __name__ == "__main__":
    try:
        if len(sys.argv) == 3:
            sys.exit(set_value(sys.argv[1], sys.argv[2]))
        else:
            print "Usage: %s [key] new_value" % sys.argv[0]
            sys.exit(1)

    except Exception as e:
        print >> sys.stderr, "ERROR: %s" % str(e)
        sys.exit(10)
